export class Employee{
   emp_id:number;
   first_name:string;
   last_name:string;
   gender:string;
   dob:Date;
   pan_num:string;
   aadhaar_num:string;
   mobile_num:string;
   email_id:string;
   office_mail:string;
   permanent_address:string;
   present_address:string;
   blood_group:string;
   profile_pict:string;
   doj:Date;
   emp_level:number;
   post_name:string;
   basic_pay:number;
   house_allowance:number;
}
